### ISSUE TITLE
Unable to encode long integers

### ISSUE THREAD

**Issue by miken32** [FreeDSx/ASN1#10]
Not 100% sure this is a bug, it could just be me missing something. I couldn't find a way to encode a large number. I'm trying to build an X.509 public key which has a 2048-bit modulus. Obviously this is not a size of "integer" that any language can handle, but should be valid as an ASN integer.

This is the closest I could get:
```php
<?php
use FreeDSx\Asn1\Asn1;
use FreeDSx\Asn1\Encoders;

require 'vendor/autoload.php';

$modulus = sodium_base642bin(
    '2EawFzigeg_kPB-euOI9JbRxmCvjC0Gi9sX80iDfVxiEqgNWfhqC8EGJ75fKo7LD63LxtRIJBgO3eZ2oGuXW7usuDcpYYw-xBe_yVHJujzFscb5lgHQ0aPW80XsGhcZJJbGZk4DCS1p4HDOzROlPMVBDXNFDa0hkbV5V92_jXRc4cC3zXIOQOTrDPYGCCddGz9z__s_n9B0mLaV4gReR_lBSigBMr3E8Qa83fRanF8sI5--5iyKe5ThCa2WcBCIfQmqZx0DtgaphSdcgnFzpVdUYrS1EmWAYzyQlT5ouvUOYzIVfIytrDyNXJEvMWamBJ_gh5zmTK1cor7pH0X9-LQ',
    SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING
);
$exponent = sodium_base642bin('AQAB', SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);

$bitstring = Encoders::der()
    ->encode(
        Asn1::sequence(
            Asn1::octetString($modulus)->setTagNumber(2),
            Asn1::octetString($exponent)->setTagNumber(2)
        )
    );

$key = Asn1::sequence(
    Asn1::sequence(Asn1::oid('1.2.840.113549.1.1.1'), Asn1::null()),
    Asn1::bitStringFromBinary($bitstring)
);

$der = Encoders::der()->encode($key);
$pem = trim(chunk_split(base64_encode($der), 64, PHP_EOL));

echo sprintf('-----BEGIN PUBLIC KEY-----%s%s%s-----END PUBLIC KEY-----%s', PHP_EOL, $pem, PHP_EOL, PHP_EOL);
```
This outputs:
```
-----BEGIN PUBLIC KEY-----
MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQDYRrAXOKB6D+Q8H5644j0l
tHGYK+MLQaL2xfzSIN9XGISqA1Z+GoLwQYnvl8qjssPrcvG1EgkGA7d5naga5dbu
6y4NylhjD7EF7/JUcm6PMWxxvmWAdDRo9bzRewaFxkklsZmTgMJLWngcM7NE6U8x
UENc0UNrSGRtXlX3b+NdFzhwLfNcg5A5OsM9gYIJ10bP3P/+z+f0HSYtpXiBF5H+
UFKKAEyvcTxBrzd9FqcXywjn77mLIp7lOEJrZZwEIh9CapnHQO2BqmFJ1yCcXOlV
1RitLUSZYBjPJCVPmi69Q5jMhV8jK2sPI1ckS8xZqYEn+CHnOZMrVyivukfRf34t
AgMBAAE=
-----END PUBLIC KEY-----
```
But my desired output is:
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2EawFzigeg/kPB+euOI9
JbRxmCvjC0Gi9sX80iDfVxiEqgNWfhqC8EGJ75fKo7LD63LxtRIJBgO3eZ2oGuXW
7usuDcpYYw+xBe/yVHJujzFscb5lgHQ0aPW80XsGhcZJJbGZk4DCS1p4HDOzROlP
MVBDXNFDa0hkbV5V92/jXRc4cC3zXIOQOTrDPYGCCddGz9z//s/n9B0mLaV4gReR
/lBSigBMr3E8Qa83fRanF8sI5++5iyKe5ThCa2WcBCIfQmqZx0DtgaphSdcgnFzp
VdUYrS1EmWAYzyQlT5ouvUOYzIVfIytrDyNXJEvMWamBJ/gh5zmTK1cor7pH0X9+
LQIDAQAB
-----END PUBLIC KEY-----
```
There's a `01` byte [before the modulus integer](https://lapo.it/asn1js/#MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2EawFzigeg_kPB-euOI9JbRxmCvjC0Gi9sX80iDfVxiEqgNWfhqC8EGJ75fKo7LD63LxtRIJBgO3eZ2oGuXW7usuDcpYYw-xBe_yVHJujzFscb5lgHQ0aPW80XsGhcZJJbGZk4DCS1p4HDOzROlPMVBDXNFDa0hkbV5V92_jXRc4cC3zXIOQOTrDPYGCCddGz9z__s_n9B0mLaV4gReR_lBSigBMr3E8Qa83fRanF8sI5--5iyKe5ThCa2WcBCIfQmqZx0DtgaphSdcgnFzpVdUYrS1EmWAYzyQlT5ouvUOYzIVfIytrDyNXJEvMWamBJ_gh5zmTK1cor7pH0X9-LQIDAQAB) which is [missing from my output](https://lapo.it/asn1js/#MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQDYRrAXOKB6D-Q8H5644j0ltHGYK-MLQaL2xfzSIN9XGISqA1Z-GoLwQYnvl8qjssPrcvG1EgkGA7d5naga5dbu6y4NylhjD7EF7_JUcm6PMWxxvmWAdDRo9bzRewaFxkklsZmTgMJLWngcM7NE6U8xUENc0UNrSGRtXlX3b-NdFzhwLfNcg5A5OsM9gYIJ10bP3P_-z-f0HSYtpXiBF5H-UFKKAEyvcTxBrzd9FqcXywjn77mLIp7lOEJrZZwEIh9CapnHQO2BqmFJ1yCcXOlV1RitLUSZYBjPJCVPmi69Q5jMhV8jK2sPI1ckS8xZqYEn-CHnOZMrVyivukfRf34tAgMBAAE) and I can't figure out how to get that working.

**Comment by ChadSikorra** [comment]
Hmmm...nothing in what you're doing looks all that unusual at first glance. But I'll also admit I haven't done much with the DER encoder yet. It just has some more strict rules. I had intended to use it for a kerberos library I was thinking about doing at one point.

I'd have to take a closer look at what's going on.  I'd be curious if decoding also encounters any issues.

**Comment by miken32** [comment]
I got it to work by passing a numeric string constructed with GMP. This required a change to the signature of `FreeDSx\Asn1\Asn1::integer()` to accept the string; the constructor for `IntegerType` was already fine with taking a string.

Working code:
```
<?php
use FreeDSx\Asn1\Asn1;
use FreeDSx\Asn1\Encoders;

require 'vendor/autoload.php';

$modulus = sodium_base642bin(
    '2EawFzigeg_kPB-euOI9JbRxmCvjC0Gi9sX80iDfVxiEqgNWfhqC8EGJ75fKo7LD63LxtRIJBgO3eZ2oGuXW7usuDcpYYw-xBe_yVHJujzFscb5lgHQ0aPW80XsGhcZJJbGZk4DCS1p4HDOzROlPMVBDXNFDa0hkbV5V92_jXRc4cC3zXIOQOTrDPYGCCddGz9z__s_n9B0mLaV4gReR_lBSigBMr3E8Qa83fRanF8sI5--5iyKe5ThCa2WcBCIfQmqZx0DtgaphSdcgnFzpVdUYrS1EmWAYzyQlT5ouvUOYzIVfIytrDyNXJEvMWamBJ_gh5zmTK1cor7pH0X9-LQ',
    SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING
);
$exponent = sodium_base642bin('AQAB', SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);

$mod_gmp = gmp_strval(gmp_init(bin2hex($modulus), 16));
$exp_gmp = gmp_strval(gmp_init(bin2hex($exponent), 16));

$bitstring = Encoders::der()
    ->encode(
        Asn1::sequence(
            Asn1::integer($mod_gmp),
            Asn1::integer($exp_gmp),
        )
    );

$key = Asn1::sequence(
    Asn1::sequence(Asn1::oid('1.2.840.113549.1.1.1'), Asn1::null()),
    Asn1::bitStringFromBinary($bitstring)
);

$der = Encoders::der()->encode($key);
$pem = trim(chunk_split(base64_encode($der), 64, PHP_EOL));

echo sprintf('-----BEGIN PUBLIC KEY-----%s%s%s-----END PUBLIC KEY-----%s', PHP_EOL, $pem, PHP_EOL, PHP_EOL);
```

**Comment by ChadSikorra** [comment]
> I got it to work by passing a numeric string constructed with GMP. This required a change to the signature of `FreeDSx\Asn1\Asn1::integer()` to accept the string; the constructor for `IntegerType` was already fine with taking a string.
> 
> Working code:
> ```
> <?php
> use FreeDSx\Asn1\Asn1;
> use FreeDSx\Asn1\Encoders;
> 
> require 'vendor/autoload.php';
> 
> $modulus = sodium_base642bin(
>     '2EawFzigeg_kPB-euOI9JbRxmCvjC0Gi9sX80iDfVxiEqgNWfhqC8EGJ75fKo7LD63LxtRIJBgO3eZ2oGuXW7usuDcpYYw-xBe_yVHJujzFscb5lgHQ0aPW80XsGhcZJJbGZk4DCS1p4HDOzROlPMVBDXNFDa0hkbV5V92_jXRc4cC3zXIOQOTrDPYGCCddGz9z__s_n9B0mLaV4gReR_lBSigBMr3E8Qa83fRanF8sI5--5iyKe5ThCa2WcBCIfQmqZx0DtgaphSdcgnFzpVdUYrS1EmWAYzyQlT5ouvUOYzIVfIytrDyNXJEvMWamBJ_gh5zmTK1cor7pH0X9-LQ',
>     SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING
> );
> $exponent = sodium_base642bin('AQAB', SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);
> 
> $mod_gmp = gmp_strval(gmp_init(bin2hex($modulus), 16));
> $exp_gmp = gmp_strval(gmp_init(bin2hex($exponent), 16));
> 
> $bitstring = Encoders::der()
>     ->encode(
>         Asn1::sequence(
>             Asn1::integer($mod_gmp),
>             Asn1::integer($exp_gmp),
>         )
>     );
> 
> $key = Asn1::sequence(
>     Asn1::sequence(Asn1::oid('1.2.840.113549.1.1.1'), Asn1::null()),
>     Asn1::bitStringFromBinary($bitstring)
> );
> 
> $der = Encoders::der()->encode($key);
> $pem = trim(chunk_split(base64_encode($der), 64, PHP_EOL));
> 
> echo sprintf('-----BEGIN PUBLIC KEY-----%s%s%s-----END PUBLIC KEY-----%s', PHP_EOL, $pem, PHP_EOL, PHP_EOL);
> ```

Yeah, this library handles ints over the PHP max int size by treating them as strings. ASN1 has no limits on the size of an integer. It would be good to update the factory method signature and add some phpdoc to it that it can be a numeric string or int.

**Comment by ChadSikorra** [comment]
I've updated the method signature for the factory method to support string or int and published a new version.
